name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: studentperformance1
  CONTAINER_PORT: 8080
  HOST_PORT: 8080

jobs:
  deploy:
    name: Build and Deploy Docker on EC2
    runs-on: self-hosted       # This will use your EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR (optional, if you want to push image)
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: eu-north-1

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Stop existing container (if any)
        run: |
          if [ $(docker ps -q -f name=$IMAGE_NAME) ]; then
            docker stop $IMAGE_NAME
            docker rm $IMAGE_NAME
          fi || true

      - name: Run container
        run: |
          docker run -d \
            --name $IMAGE_NAME \
            -p $HOST_PORT:$CONTAINER_PORT \
            $IMAGE_NAME
