name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build & Run on EC2
    runs-on: self-hosted   # Your EC2 runner must be registered

    env:
      IMAGE_NAME: studentperformance1
      CONTAINER_NAME: studentperformance1
      CONTAINER_PORT: 8080
      AWS_REGION: eu-north-1
      ECR_REGISTRY: 585008067217.dkr.ecr.eu-north-1.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: ${{ env.ECR_REGISTRY }}
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Stop old container if exists
      run: |
        if [ $(docker ps -q -f name=$CONTAINER_NAME) ]; then
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
        fi || true

    - name: Run Docker container
      run: |
        docker run -d \
          --name $CONTAINER_NAME \
          -p $CONTAINER_PORT:$CONTAINER_PORT \
          $ECR_REGISTRY/$IMAGE_NAME:latest
