name: Deploy to EC2 via Runner

on:
  push:
    branches:
      - main
      

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: studentperformance1   # your ECR repo name
  IMAGE_TAG: latest                     # or use Git commit SHA
  CONTAINER_NAME: studentperformance1
  CONTAINER_PORT: 8080

jobs:
  deploy:
    runs-on: self-hosted   # runs on your EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 585008067217.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Pull Docker image
        run: |
          docker pull 585008067217.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Stop previous container if running
        run: |
          docker ps -q --filter "name=$CONTAINER_NAME" | xargs -r docker stop
          docker ps -a -q --filter "name=$CONTAINER_NAME" | xargs -r docker rm

      - name: Run Docker container
        run: |
          docker run -d --name $CONTAINER_NAME -p $CONTAINER_PORT:$CONTAINER_PORT 585008067217.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
